#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
    # create user
    adduser --system --quiet --home /var/tmp --no-create-home --group sentry

    # create sample configuration file
    if [ ! -e /etc/sentry/sentry.conf.py ]; then
        mkdir -p /etc/sentry
        chown sentry:sentry /etc/sentry
        sudo -u sentry /opt/venvs/sentry/bin/sentry init /etc/sentry
    else
        # migrate
        sudo -u sentry /opt/venvs/sentry/bin/sentry --config /etc/sentry upgrade
    fi
fi
